#!/bin/bash

# Listmonk Setup Script for Heavenletters
# Compatible with existing Mailu mail server

set -e

echo "🚀 Setting up Listmonk for Heavenletters..."
echo "============================================="

# Check if Docker is running
if ! docker info > /dev/null 2>&1; then
    echo "❌ Docker is not running. Please start Docker first."
    exit 1
fi

# Create directories
echo "📁 Creating directories..."
sudo mkdir -p /opt/listmonk
sudo mkdir -p /opt/listmonk/uploads

# Set proper permissions
sudo chown -R $USER:$USER /opt/listmonk

# Create .env file from template
echo "🔐 Setting up environment configuration..."
if [ ! -f /opt/listmonk/.env ]; then
    if [ -f .env.template ]; then
        cp .env.template /opt/listmonk/.env
        echo "✅ Created .env file from template"
    else
        echo "⚠️  .env.template not found, creating basic .env file..."
        cat > /opt/listmonk/.env << 'EOF'
# Listmonk Environment Configuration
# Generated by setup script - update these values for security

# Database Configuration
POSTGRES_USER=listmonk_user
POSTGRES_PASSWORD=CHANGE_THIS_TO_A_SECURE_PASSWORD_123!@#
POSTGRES_DB=listmonk_db

# Listmonk Configuration
LISTMONK_ADMIN_USER=admin
LISTMONK_ADMIN_PASSWORD=CHANGE_THIS_TO_A_SECURE_ADMIN_PASSWORD_456!@#

# Application Settings
LISTMONK_app__address=0.0.0.0:9000
LISTMONK_db__host=listmonk_db
LISTMONK_db__port=5432
LISTMONK_db__ssl_mode=disable
LISTMONK_db__max_open=25
LISTMONK_db__max_idle=25
LISTMONK_db__max_lifetime=300s

# Timezone
TZ=Etc/UTC
EOF
    fi
else
    echo "✅ .env file already exists"
fi

# Generate secure passwords if defaults are still in use
if grep -q "CHANGE_THIS_TO_A_SECURE_PASSWORD" /opt/listmonk/.env; then
    echo "🔑 Generating secure passwords..."
    DB_PASSWORD=$(openssl rand -base64 32)
    ADMIN_PASSWORD=$(openssl rand -base64 32)

    # Update .env file with secure passwords
    sed -i "s/CHANGE_THIS_TO_A_SECURE_PASSWORD_123!@#/$DB_PASSWORD/" /opt/listmonk/.env
    sed -i "s/CHANGE_THIS_TO_A_SECURE_ADMIN_PASSWORD_456!@#/$ADMIN_PASSWORD/" /opt/listmonk/.env

    echo "✅ Generated secure passwords in .env file"
fi

# Download the Docker Compose file
echo "📋 Downloading Docker Compose configuration..."
cat > /opt/listmonk/docker-compose.yml << 'EOF'
# Listmonk Docker Compose - Standalone Configuration
# Compatible with Mailu mail server setup
# No port conflicts, isolated networks and volumes

version: '3.8'

# Database credentials - change these for security
x-db-credentials: &db-credentials
  POSTGRES_USER: listmonk_user
  POSTGRES_PASSWORD: ChangeThisToASecurePassword123!
  POSTGRES_DB: listmonk_db

services:
  # Listmonk application
  listmonk:
    image: listmonk/listmonk:latest
    container_name: listmonk_app
    restart: unless-stopped

    # Port configuration - no conflicts with Mailu
    ports:
      - "127.0.0.1:9000:9000"  # Only accessible locally for security

    # Network configuration - isolated from Mailu
    networks:
      - listmonk_network
    hostname: listmonk.heavenletters.local

    # Startup command with auto-install and upgrade
    command: >
      sh -c "./listmonk --install --idempotent --yes --config '' &&
             ./listmonk --upgrade --yes --config '' &&
             ./listmonk --config ''"

    # Environment variables for configuration
    environment:
      # Application settings
      LISTMONK_app__address: 0.0.0.0:9000

      # Database connection settings
      LISTMONK_db__host: listmonk_db
      LISTMONK_db__port: 5432
      LISTMONK_db__user: *db-user
      LISTMONK_db__password: *db-password
      LISTMONK_db__database: *db-name
      LISTMONK_db__ssl_mode: disable
      LISTMONK_db__max_open: 25
      LISTMONK_db__max_idle: 25
      LISTMONK_db__max_lifetime: 300s

      # Timezone
      TZ: Etc/UTC

    # Volume mounts
    volumes:
      - listmonk_uploads:/listmonk/uploads:rw

    # Health and dependencies
    depends_on:
      listmonk_db:
        condition: service_healthy

    # Logging (optional - matches Mailu's journald approach)
    logging:
      driver: journald
      options:
        tag: listmonk

  # PostgreSQL database
  listmonk_db:
    image: postgres:17-alpine
    container_name: listmonk_db
    restart: unless-stopped

    # Database port - no conflict with Mailu
    ports:
      - "127.0.0.1:5433:5432"  # Changed from 5432 to avoid any potential conflicts

    # Network configuration
    networks:
      - listmonk_network

    # Database credentials
    environment:
      <<: *db-credentials

    # Health check
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listmonk_user -d listmonk_db"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 30s

    # Persistent data storage
    volumes:
      - listmonk_db_data:/var/lib/postgresql/data

    # Logging
    logging:
      driver: journald
      options:
        tag: listmonk-db

# Networks - completely isolated from Mailu
networks:
  listmonk_network:
    driver: bridge
    name: listmonk_network
    ipam:
      driver: default
      config:
        - subnet: 192.168.205.0/24  # Different subnet from Mailu (192.168.203.0/24)

# Volumes - different paths from Mailu (/vmail/*)
volumes:
  listmonk_db_data:
    name: listmonk_db_data
  listmonk_uploads:
    name: listmonk_uploads
EOF

# Navigate to the directory
cd /opt/listmonk

# Start the services
echo "🐳 Starting Listmonk services..."
docker compose up -d

# Wait for services to be ready
echo "⏳ Waiting for services to initialize..."
sleep 10

# Check if services are running
if docker compose ps | grep -q "Up"; then
    echo "✅ Listmonk is running successfully!"
    echo ""
    echo "🌐 Access Listmonk:"
    echo "   Local: http://localhost:9000"
    echo "   Server: http://$(hostname -I | awk '{print $1}'):9000"
    echo ""
    echo "📊 Database:"
    echo "   Host: localhost"
    echo "   Port: 5433"
    echo "   Database: listmonk_db"
    echo "   User: listmonk_user"
    echo "   Password: ChangeThisToASecurePassword123!"
    echo ""
    echo "⚠️  SECURITY REMINDER:"
    echo "   - Change the default database password"
    echo "   - Set up admin credentials on first login"
    echo "   - Consider using a reverse proxy for production access"
    echo ""
    echo "📁 File locations:"
    echo "   Config: /opt/listmonk/docker-compose.yml"
    echo "   Data: /opt/listmonk/ (Docker volumes)"
    echo "   Uploads: /opt/listmonk/uploads/"
else
    echo "❌ Failed to start Listmonk. Check logs:"
    docker compose logs
    exit 1
fi

echo "🎉 Setup complete! Ready to import your Heavenletters subscriber data."