<?php
// $Id: localizermenu.install,v 1.2.2.1 2008/07/15 08:52:07 robertogerola Exp $

function localizermenu_install() {
  db_query("UPDATE {system} SET weight = 1 WHERE name = 'localizermenu'");
}

function localizermenu_update_1() {
  $items = array();
  $items[] = update_sql("UPDATE {system} SET weight = 1 WHERE name = 'localizermenu'");
  return $items;
}

function localizermenu_uninstall() {
  db_query("DELETE FROM {system} WHERE name LIKE 'localizermenu'");
}

