<?php

//$Id: emailalias.module,v 0.0.0.1 2008/08/08 19:00:00 dagmar Exp $

/**
 * Implementation of hook_form_alter().
 */
function emailalias_form_alter($form_id, &$form) {
  if ($form_id == 'system_site_information_settings') {
    $form['site_name']['#weight'] = -2;
    $form['site_mail']['#weight']  = -1;
    $form['email_alias'] = array(
        '#type' => 'textfield',
        '#title' => t('E-mail alias'),
        '#description' => t('Here you can specify a "Name" for the email like Drupal Site, instead of admin@yoursite.com'),
        '#weight' => 0,
        '#size' => 60,
        '#default_value' => variable_get('email_alias',''),
    );
    
  }
}


/**
 * Implementation of hook_mail_alter().
 */
function emailalias_mail_alter(&$mailkey, &$to, &$subject, &$body, &$from, &$headers) {
  $alias = variable_get('email_alias', 0);
  $sitemail = variable_get('site_mail', '');
  if (($from == $sitemail || $from == NULL) && $alias) {
    $headers['From'] = $alias . ' <' . $sitemail . '>';
  }
}