<?php
// $Id: tellafriend.module,v 1.11 2008/06/12 22:41:16 thierrygd Exp $

/**
 * @file
 * Enables "send to a friend" functionality
 */

ini_set('SMTP', variable_get('tellafriend_server', 'localhost'));
// Users are not allowed to send more than x mails/hour:
define('TELLAFRIEND_DEFAULT_HOURLY_THRESHOLD', 10);
// By default, users are not allowed to include more than y e-mail addresses per request.  
// This value can be changed via the tell-a-friend settings page.
define('TELLAFRIEND_DEFAULT_MAX_EMAIL_ADDRESSES', 10);

/**
 * Implementation of hook_help().
 */
function tellafriend_help($section) {
  switch ($section) {
    case 'admin/help#poll':
      return t("Access page at: tellafriend");
    case 'admin/modules#description':
      return t("Allows you to create a Tell-a-Friend page to spread the word about your site.");
    case 'admin/help#tellafriend':
      global $base_url;
      return t("Access <em>Tell a friend</em> page at: !path", array('!path' => 
      	l($base_url . urldecode('/?q=tellafriend'), 'tellafriend')));      
  }
}

/**
 * Implementation of hook_perm().
 */
function tellafriend_perm() {
  return array('access tellafriend form');
}

/**
* Implementation of hook_menu().
*/
function tellafriend_menu() {
  $items = array();
    
    $items[] = array(
      'path' => 'admin/settings/tellafriend',
      'title' => t('Tell a friend'),
      'description' => t('Control the contents of <em>Tell a friend</em> e-mail message.'),
      'callback' => 'drupal_get_form',
      'callback arguments' => 'tellafriend_settings',
      'access' => user_access('administer site configuration'),
      'type' => MENU_NORMAL_ITEM,
    );
    $items[] = array(
      'path' => 'tellafriend',
      'title' => variable_get('tellafriend_pagetitle', t('Tell a friend')),
      'callback' => 'drupal_get_form',
      'callback arguments' => 'tellafriend_page',
      'access' => user_access('access tellafriend form'),
      'type' => MENU_CALLBACK,
    );

  return $items;
}

/**
 * Implementation of hook_settings().
 */
function tellafriend_settings() {

  $form['tellafriend_general'] = array(
    '#type' => 'fieldset',
    '#title' => t('General settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['tellafriend_general']['tellafriend_pagetitle'] = array(
    '#type' => 'textfield',
    '#title' => t('Page title'),
    '#default_value' => variable_get('tellafriend_pagetitle', t('Tell a friend')),
    '#size' => 70,
    '#maxlength' => 200,
    '#description' => t('Title of the <em>Tell a friend</em> page.'),
  );
  $form['tellafriend_general']['tellafriend_topmessage'] = array(
    '#type' => 'textarea',
    '#title' => t('Top Message'),
    '#default_value' => variable_get('tellafriend_topmessage', t('Spread the word about !site by telling your friend(s) about it!', array('!site' => variable_get('site_name', 'Drupal')))),
    '#size' => 70,
    '#rows' => 5,
    '#description' => t('A description or information shown above the <em>Tell a friend</em> form.'),
  );
  $form['tellafriend_general']['tellafriend_success'] = array(
    '#type' => 'textfield',
    '#title' => t('Success redirect path'),
    '#default_value' => variable_get('tellafriend_success', variable_get('site_frontpage', 'node')),
    '#size' => 70,
    '#maxlength' => 200,
    '#description' => t('This is where the script will redirect the user after the e-mail is successfully sent.'),
  );
  $form['tellafriend_general']['tellafriend_server'] = array(
    '#type' => 'textfield',
    '#title' => t('Server name'),
    '#default_value' => variable_get('tellafriend_server', 'localhost'),
    '#size' => 70,
    '#maxlength' => 200,
    '#description' => t('SMTP server name. Default is <em>localhost</em>.'),
  );
  $form['tellafriend_general']['tellafriend_hourly_threshold'] = array(
    '#type' => 'textfield',
    '#title' => t('Hourly Threshold'),
    '#default_value' => variable_get('tellafriend_hourly_threshold', TELLAFRIEND_DEFAULT_HOURLY_THRESHOLD),
    '#size' => 30,
    '#maxlength' => 40,
    '#description' => t('This is the maximum number of tell-a-friend requests per user, per hour.'),
  );
  $form['tellafriend_general']['tellafriend_address_limit'] = array(
    '#type' => 'textfield',
    '#title' => t('Address Limit'),
    '#default_value' => variable_get('tellafriend_address_limit', TELLAFRIEND_DEFAULT_MAX_EMAIL_ADDRESSES),
    '#size' => 30,
    '#maxlength' => 40,
    '#description' => t('This is the maximum number of email addresses that can be included per tell-a-friend request.'),
  );
  
  $form['tellafriend_block'] = array(
    '#type' => 'fieldset',
    '#title' => t('Block settings'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['tellafriend_block']['tellafriend_block_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Block Title'),
    '#default_value' => variable_get('tellafriend_block_title', t("Spread the world...")),
    '#size' => 70,
    '#maxlength' => 128,
    '#description' => t('This will be the title for the tellafriend block (if activated : go to admin/build/block to activate or not the block).'),
  );  
  $form['tellafriend_block']['tellafriend_block_linklabel'] = array(
    '#type' => 'textfield',
    '#title' => t('Link label'),
    '#default_value' => variable_get('tellafriend_block_linklabel', t("Tell a friend...")),
    '#size' => 70,
    '#maxlength' => 128,
    '#description' => t('This will be the link which will appear in the tellafriend block.'),
  );    
  $form['tellafriend_mail'] = array(
    '#type' => 'fieldset',
    '#title' => t('E-mail template'),
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
  );
  $form['tellafriend_mail']['tellafriend_fromaddress'] = array(
    '#type' => 'textfield',
    '#title' => t('From address'),
    '#default_value' => variable_get('tellafriend_fromaddress', ''),
    '#size' => 70,
    '#maxlength' => 200,
    '#description' => t("This is the address the e-mail will come from. Site e-mail address is %sitemail. Leave blank to use sender's e-mail address", array('%sitemail' => variable_get('site_mail', ini_get('sendmail_from')))),
  );
  $form['tellafriend_mail']['tellafriend_subject'] = array(
    '#type' => 'textfield',
    '#title' => t('Email Subject'),
    '#default_value' => variable_get('tellafriend_subject', t('!sendername has invited you to !sitename!')),
    '#size' => 70,
    '#maxlength' => 200,
    '#description' => t('This is the e-mail subject. Available placeholders: <em>!sitename, !sitelink, !sitemail, !sendername, !sendermail</em>.'),
  );
  $form['tellafriend_mail']['tellafriend_message'] = array(
    '#type' => 'textarea',
    '#title' => t('Message Text'),
    '#default_value' => variable_get('tellafriend_message', t('You are invited to check out !sitename at !sitelink')),
    '#cols' => 70,
    '#rows' => 5,
    '#description' => t('This is the text of the sent message. Use plain text only. Available placeholders: <em>!sitename, !sitelink, !sitemail, !sendername, !sendermail</em>.'),
  );
  $form['tellafriend_mail']['tellafriend_closing'] = array(
    '#type' => 'textfield',
    '#title' => t('Closing'),
    '#default_value' => variable_get('tellafriend_closing', t('Sincerely,')),
    '#size' => 70,
    '#maxlength' => 200,
    '#description' => t('Love, Sincerely, etc...'),
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_block
 * - Block lists N upcoming birthdays
 * - Block lists birthdays in N days
 *
 * @param $op the operation that is being requested.  This defaults to 'list', which indicates that the method should
 *        return which blocks are available.
 * @param $delta the specific block to display.  This is actually the offset into an array.
 * @return one of two possibilities.  The first is an array of available blocks.  The other is an array containing a
 *
 */
function tellafriend_block($op = 'list', $delta = 0) {
  // The $op parameter determines what piece of information is being requested.
  if ($op == 'list') {
    // If $op is "list", we just need to return a list of block descriptions. This
    // is used to provide a list of possible blocks to the administrator.
    $blocks[0]['info'] = t("Tell a friend");
    return $blocks;
  }
  else if ($op == 'save' && $delta == 0) {
      variable_set('tellafriend_block_title', $edit['tellafriend_block_title']);
  }
  else if ($op == 'view') {
      switch ($delta) {
	  case 0:
	  $block = array();
	  if (user_access('access tellafriend form')) {
	     $blockContent .= '<ul><li class="leaf">' . l(t(variable_get('tellafriend_block_linklabel', t("Tell a friend..."))), 'tellafriend') . '</li></ul>';
	     $block['content'] = $blockContent;
    	     $block['subject'] = variable_get('tellafriend_block_title', t("Spread the world..."));
	  }
      }
      return $block;
  }
}

/**
 * Generates the form for the page
 */
function tellafriend_page() {
  global $user;
  global $base_url;
  $placeholder_values = array('!sitename' => variable_get('site_name', 'Drupal'),'!sitelink' => $base_url,'!sitemail' => variable_get('site_mail', ini_get('sendmail_from')), '!sendername' => $form_values['tellafriend_name'], '!sendermail' => $form_values['tellafriend_email']);

  $form['#token'] = $user->name . $user->mail;
  $form['tellafriend_information'] = array('#value' => filter_xss_admin(variable_get('tellafriend_topmessage', t('Spread the word about !site by telling your friend(s) about it!', array('!site' => variable_get('site_name', 'Drupal'))))));
  $form['tellafriend_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Your name'),
    '#default_value' => ($user->uid ? $user->name : ''),
    '#size' => 70,
    '#maxlength' => 255,
    '#required' => TRUE,
    '#description' => t('Your name as it will appear in the sent e-mail.'),
  );
  $form['tellafriend_email'] = array(
    '#type' => 'textfield',
    '#title' => t('Your e-mail address'),
    '#default_value' => ($user->uid ? $user->mail : ''),
    '#size' => 70,
    '#maxlength' => 255,
    '#required' => TRUE,
    '#description' => t('Your e-mail address as it will appear in the sent e-mail.'),
  );
  $form['tellafriend_addresses'] = array(
    '#type' => 'textfield',
    '#title' => t("Your friend's e-mail address"),
    '#size' => 70,
    '#maxlength' => 255,
    '#required' => TRUE,
    '#description' => t('Separate multiple e-mail addresses with commas.'),
  );
  $form['tellafriend_personal'] = array(
    '#type' => 'textarea',
    '#title' => t('Your Personal message'),
    '#default_value' => t('I found this great web site, which you should really check out!'),
    '#cols' => 70,
    '#rows' => 5,
    '#description' => t('Add your personal message to the e-mail.'),
  );
  $form['tellafriend_copy'] = array(
    '#type' => 'checkbox',
    '#title' => t('Send yourself a copy.'),
  );
  $form['tellafriend_message'] = array('#value' => filter_xss_admin("<strong>".t('Message to be sent').":</strong><br />" . nl2br(t(variable_get('tellafriend_message', 'You are invited to check out !sitename at !sitelink'), $placeholder_values)) . '<br/>'));  
  
  $form['submit'] = array('#type' => 'submit',
    '#value' => t('Tell now!'),
  );

  return $form;
}

/**
 * Implementation of hook_validate().
 */
function tellafriend_page_validate($form_id, $form_values) {
  $tellafriend_personal = $form_values['tellafriend_personal'];

   if (!valid_email_address($form_values['tellafriend_email'])) {
        form_set_error("tellafriend_email", t('Email address is not valid!'));
   }

  $addresses = explode(",", $form_values['tellafriend_addresses']);
 
  if(count($addresses) > variable_get('tellafriend_address_limit', TELLAFRIEND_DEFAULT_MAX_EMAIL_ADDRESSES)) {
 	  form_set_error("tellafriend_addresses", 
 	  t('You have exceeded the maximum number of %number email addresses per request.', 
 	  array('%number' => variable_get('tellafriend_address_limit', TELLAFRIEND_DEFAULT_MAX_EMAIL_ADDRESSES))));
  }
 
  foreach ($addresses as $mail) {
       	$sendaddress = stripslashes(trim($mail));
       	
    	if (!valid_email_address($sendaddress)) {
    		$count++;
      		$invalid .= $sendaddress .' ';   
    	}
  	if ($invalid != '') {
    		form_set_error("tellafriend_addresses", t(format_plural(count($count), '@invalid is invalid send-to e-mail addresses.', '@invalid are invalid send-to e-mail addresses.'), array('@invalid' => $invalid)));
  	}
  }
  
  //Check that flood control has not been surpassed
  $my_threshold = variable_get('tellafriend_hourly_threshold', TELLAFRIEND_DEFAULT_HOURLY_THRESHOLD);
  if (!flood_is_allowed('tellafriend', $my_threshold)) {
  	$tellafriend_validated = 1;
  	form_set_error('', t("You can't make more than %number mail requests per hour. Please try again later.", array('%number' => variable_get('tellafriend_hourly_threshold', TELLAFRIEND_DEFAULT_HOURLY_THRESHOLD))));
  	watchdog('mail', t('%name has attempted to surpass the flood control for tellafriend.module', array('%name' => $user->name)));
  }  
}

/**
 * Implementation of hook_submit().Process the personal contact page form submission.
 */
function tellafriend_page_submit($form_id, $form_values) {
  global $base_url;
  $placeholder_values = array('!sitename' => variable_get('site_name', 'Drupal'),'!sitelink' => $base_url,'!sitemail' => variable_get('site_mail', ini_get('sendmail_from')), '!sendername' => $form_values['tellafriend_name'], '!sendermail' => $form_values['tellafriend_email']);
  $closing = variable_get('tellafriend_closing', 'Sincerely,');
  //$from = variable_get('tellafriend_fromaddress', $form_values['tellafriend_email']);
  $from = $form_values['tellafriend_name']. "<".$form_values['tellafriend_email']. ">";
  $addresses = explode(",", $form_values['tellafriend_addresses']);
  $subject = stripslashes(t(variable_get('tellafriend_subject', t('!sendername has invited you to !sitename!')), $placeholder_values));
 
  if(strlen($form_values['tellafriend_personal'])) {
    $body .= t("\nPersonal Message: ") . $form_values['tellafriend_personal'] . "\n----------------------\n\n";
  }
  $body .= t(variable_get('tellafriend_message', t('You are invited to check out !sitename at !sitelink')), $placeholder_values) ."\n$closing \n". $form_values['tellafriend_name'] ." - ". $form_values['tellafriend_email'];
 
  foreach ($addresses as $key => $mail) {
    $sendaddress[$key] = stripslashes(trim($mail));
    drupal_mail('tellafriend-page-mail', $sendaddress[$key], $subject, $body, $from);
  }
  if ($form_values['tellafriend_copy']) {
    drupal_mail('tellafriend-page-copy', $form_values['tellafriend_email'], $subject, $body, $from);
  }
  
  flood_register_event('tellafriend');  
 
  $addresses = implode(', ', $sendaddress);
  watchdog('mail', t('%sender sent an e-mail to %recepient using <em>Tell a friend</em> form.', array('%sender' => $form_values['tellafriend_name'], '%recepient' => $addresses)));
  drupal_set_message(t('Thank you! Your message has been sent to: !recepient', array('!recepient' => $addresses)));
  drupal_goto(variable_get('tellafriend_success', variable_get('site_frontpage', 'node')));
}


